name: ssh-krb-node-executor
rundeckPluginVersion: 1.2
author: Akos Hencz
date: 27/05/2017
version: 1.4
providers:
    - name: ssh-krb
      service: NodeExecutor
      title: SSH Kerberos Executor
      description: Execute a command on a remote node using SSH, authenticating using a Kerberos ticket
      plugin-type: script
      script-interpreter: /bin/bash
      script-file: ssh-krb-executor.sh
      script-args: ${node.username} ${node.hostname} ${exec.command}
      config:
        - name: kerberos_user
          title: Kerberos user
          type: String
          required: true
          description: "The user who gets Kerberos tickets using the keytab"
        - name: kerberos_keytab
          title: Kerberos keytab
          type: String
          required: true
          description: "The path and filename to the Kerberos key table used to authenticate the user (e.g. /tmp/user.ktab)"
        - name: do_kdestroy
          title: Destroy kerberos ticket
          type: Boolean
          required: true
          description: "If selected, the kerberos ticket will be destroyed at the end of the execution"

    - name: scp-krb
      service: FileCopier
      title: SCP Kerberos Executor
      description: Copies the file to a remote node using SCP, authenticating using a Kerberos ticket
      plugin-type: script
      script-interpreter: /bin/bash
      script-file: scp-krb-executor.sh
      script-args: ${node.username} ${node.hostname} ${file-copy.file} ${file-copy.destination}
      config:
        - name: kerberos_user
          title: Kerberos user
          type: String
          required: true
          description: "The user who gets Kerberos tickets using the keytab"
        - name: kerberos_keytab
          title: Kerberos keytab
          type: String
          required: true
          description: "The path and filename to the Kerberos key table used to authenticate the user (e.g. /tmp/user.ktab)"
        - name: do_kdestroy
          title: Destroy kerberos ticket
          type: Boolean
          required: true
          description: "If selected, the kerberos ticket will be destroyed at the end of the execution"
